[package]
name = "pd-ext"
version = "0.1.0"
authors = ["Alex Norman <alex@x37v.info>"]
edition = "2018"
build = "build.rs"
license = "BSD-3-Clause"
homepage = "https://github.com/x37v/puredata-rust"
keywords = ["audio", "sound", "music", "puredata", "multimedia"]
categories = ["multimedia::audio", "multimedia::video", "multimedia::images"]
description = "Rustified wrappers around and bindings for pd-sys for building Pure Data Externals"

[dependencies]
pd-sys = "0.1.1"
field-offset = "0.1.1"

[build-dependencies]
quote = "0.6.13"
syn = "0.15.42"
proc-macro2 = "0.4.30"
